export const genres = ["pop","dance pop","rap","pop rap","rock",
  "post-teen pop","hip hop","trap music","r&b","latin","modern rock",
  "tropical house","electropop","edm","southern hip hop","latin pop",
  "pop rock","tropical","post-grunge","album rock","alternative metal",
  "mellow gold","soft rock","folk-pop","neo mellow","classic rock",
  "permanent wave","indie rock","reggaeton","contemporary country",
  "nu metal","hard rock","pop punk","electro house","alternative rock",
  "urban contemporary","indie folk","indie pop","atl hip hop","viral pop",
  "country road","folk rock","country","k-pop","rock en espanol","underground hip hop",
  "gangster rap","uk pop","latin hip hop","canadian pop","big room","indietronica",
  "german hip hop","grupera","french hip hop","funk carioca","indie poptimism",
  "trap latino","house","reggaeton flow","garage rock","latin alternative",
  "chamber pop","mexican pop","dance rock","art rock","regional mexican",
  "new wave pop","latin rock","stomp and holler","emo rap","trap francais",
  "alternative r&b","europop","hip pop","banda","adult standards","new wave",
  "australian pop","vapor trap","conscious hip hop","psychedelic rock","progressive house",
  "christmas","progressive electro house","miami hip hop","norteno","soul","sertanejo universitario",
  "modern country rock","latin arena pop","metal","pop edm","boy band","chicago rap","neo soul",
  "funk","roots rock","indie cafe pop","indie r&b","rap rock","canadian hip hop","singer-songwriter",
  "regional mexican pop","colombian pop","glam rock","swedish pop","folk","quiet storm","motown",
  "disco","lo-fi beats","italian hip hop","new rave","brostep","blues-rock","ranchera","spanish pop",
  "ccm","new americana","emo","new romantic","focus","art pop","uk dance","screamo","rap metal",
  "alternative dance","metropopolis","east coast hip hop","worship","hardcore hip hop","g funk","punk",
  "christian music","indie anthem-folk","hollywood","dutch pop","vapor soul","escape room","southern rock",
  "mpb","deep pop r&b","brill building pop","electronic","piano rock","sertanejo pop","pagode","sleep",
  "chillhop","country rock","cumbia","world worship","acoustic pop","sertanejo","german pop","country pop",
  "italian pop","talent show","uk hip hop","metalcore","argentine rock","electronic trap","groove metal",
  "modern alternative rock","dirty south rap","brazilian electronica","west coast rap","hoerspiel",
  "dutch hip hop","funk ostentacao","baile pop","dark trap","classic soul","soundtrack","detroit hip hop",
  "glam metal","heartland rock","deep big room","christian alternative rock","dance-punk","j-pop","opm",
  "scorecore","vocal jazz","pop nacional","italian arena pop","brazilian hip hop","yacht rock",
  "melodic metalcore","outlaw country","deep german hip hop","cantautor","rap conscient","anthem worship",
  "british invasion","deep tropical house","classical","lounge","alternative hip hop","brazilian rock",
  "dream pop","indie pop rap","nova mpb","turkish pop","francoton","funk metal","mexican rock","cali rap",
  "traditional country","norwegian pop","canadian contemporary r&b","show tunes","australian indie",
  "rock-and-roll","grime","shimmer pop","british soul","speed metal","indiecoustica","deep house",
  "turkish rock","new jack swing","otacore","indonesian pop","girl group","britpop","freak folk",
  "grunge","chillwave","synthpop","australian dance"];